version: "3"

# container to compile .proto files
services:
  # Golang
  golang:
    build:
      context: ../
      dockerfile: ./docker/golang/Dockerfile
      args:
        HTTP_PROXY: "${HTTP_PROXY}"
        HTTPS_PROXY: "${HTTPS_PROXY}"
        LANG_VERSION: "1.11.0"
        PROTOC_VERSION: "3.6.1"
        WORK_DIR: "/go/src/golang/"
    image: "mythrnr/grpccompiler.golang:latest"
    command: sh compile.sh
    volumes:
      - ${GRPC_COMPILER_DIR_PROTO:-../example/proto}:/go/src/proto/:ro
      - ${GRPC_COMPILER_DIR_GOLANG:-../example/golang}:/go/src/golang/:rw
      - ./golang/compile.sh:/go/src/golang/compile.sh

  # PHP
  php:
    build:
      context: ../
      dockerfile: ./docker/php/Dockerfile
      args:
        HTTP_PROXY: "${HTTP_PROXY}"
        HTTPS_PROXY: "${HTTPS_PROXY}"
        LANG_VERSION: "7.2.9"
        PROTOC_VERSION: "3.6.1"
        WORK_DIR: "/usr/src/php/"
    image: "mythrnr/grpccompiler.php:latest"
    command: sh compile.sh
    volumes:
      - ${GRPC_COMPILER_DIR_PROTO:-../example/proto}:/usr/src/proto/:ro
      - ${GRPC_COMPILER_DIR_PHP:-../example/php}:/usr/src/php/:rw
      - ./php/compile.sh:/usr/src/php/compile.sh
