# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services/user.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from messages import user_pb2 as messages_dot_user__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='services/user.proto',
  package='sample.services',
  syntax='proto3',
  serialized_options=_b('Z\010services\312\002\017Sample\\Services'),
  serialized_pb=_b('\n\x13services/user.proto\x12\x0fsample.services\x1a\x13messages/user.proto2D\n\x0bUserService\x12\x35\n\x03Get\x12\x15.sample.messages.User\x1a\x15.sample.messages.User\"\x00\x42\x1cZ\x08services\xca\x02\x0fSample\\Servicesb\x06proto3')
  ,
  dependencies=[messages_dot_user__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)


DESCRIPTOR._options = None

_USERSERVICE = _descriptor.ServiceDescriptor(
  name='UserService',
  full_name='sample.services.UserService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=61,
  serialized_end=129,
  methods=[
  _descriptor.MethodDescriptor(
    name='Get',
    full_name='sample.services.UserService.Get',
    index=0,
    containing_service=None,
    input_type=messages_dot_user__pb2._USER,
    output_type=messages_dot_user__pb2._USER,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_USERSERVICE)

DESCRIPTOR.services_by_name['UserService'] = _USERSERVICE

# @@protoc_insertion_point(module_scope)
